# Generated by Django 5.2.9 on 2026-05-12 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={'verbose_name': 'Ranking', 'verbose_name_plural': 'Rankings'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(null=True, verbose_name='Data de lançamento'),
        ),
        migrations.AlterField(
            model_name='game',
            name='revenue_1year',
            field=models.FloatField(null=True, verbose_name='Receita (1 ano)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='review_count',
            field=models.IntegerField(null=True, verbose_name='Avaliações'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Jogo'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='position',
            field=models.IntegerField(verbose_name='Posição'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Jogo'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tag'),
        ),
    ]
